redis:
    port: 6379
    host: "127.0.0.1"
    path: "" # you don't need this if you don't know what it is
    password: ""
    database: 1 # change this if you're running multiple databases on redis

config:
    server: 'irc.rizon.net'
    port: 6697
    ssl: true
    channels: ['#homescreen']

    nick: 'kekbot'
    realname: 'kekbot'
    password: '' # note that this is not the nickserv pass
    nickserv: 'no'
    nspassword: '' # this is
