redis:
    port: 6379
    host: "127.0.0.1"
    path: "" 
    password: ""

config:
    server: irc.rizon.net
    port: 6667
    nick: kekbot
    channels: ['#homescreen', '#fsf']
    realname: kekbot
    password: dudeweedlmao
